/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.autolavado.view;

import java.awt.*;



/**
 *
 * @author PC-12
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        submnuRols = new javax.swing.JMenuItem();
        submnuUsuarios = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        submnuClientes = new javax.swing.JMenuItem();
        submnuVehiculos = new javax.swing.JMenuItem();
        mnuServicios = new javax.swing.JMenu();
        submnuServicios = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        submnuVentas = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setTitle("Sistema de Control de Autolavados");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen3.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });

        submnuRols.setText("Registrar Rols");
        submnuRols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuRolsActionPerformed(evt);
            }
        });
        mnuUsuarios.add(submnuRols);

        submnuUsuarios.setText("Registrar Usuarios");
        submnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(submnuUsuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen4.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        submnuClientes.setText("Registrar Clientes");
        submnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuClientes);

        submnuVehiculos.setText("Registrar Vehiculo");
        submnuVehiculos.setActionCommand("Registrar Vehiculos");
        submnuVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVehiculosActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuVehiculos);

        jMenuBar1.add(mnuClientes);

        mnuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen5.png"))); // NOI18N
        mnuServicios.setText("Servicios");

        submnuServicios.setText("Registrar Servicios");
        submnuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuServiciosActionPerformed(evt);
            }
        });
        mnuServicios.add(submnuServicios);

        jMenuBar1.add(mnuServicios);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen6.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        submnuVentas.setText("Registrar Ventas");
        submnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVentasActionPerformed(evt);
            }
        });
        mnuVentas.add(submnuVentas);

        jMenuBar1.add(mnuVentas);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen7.png"))); // NOI18N
        mnuReportes.setText("Reportes");
        jMenuBar1.add(mnuReportes);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen8.png"))); // NOI18N
        mnuSalir.setText("Salir");
        jMenuBar1.add(mnuSalir);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ayudita.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");
        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submnuRolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuRolsActionPerformed
        // TODO add your handling code here:
        FrmRols formrols = new FrmRols();
        Desktop.add(formrols);
        formrols.setVisible(true);
    }//GEN-LAST:event_submnuRolsActionPerformed

    private void submnuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuServiciosActionPerformed
        // TODO add your handling code here:
        FrmServicios formservicios = new FrmServicios();
        Desktop.add(formservicios);
        formservicios.setVisible(true);
    }//GEN-LAST:event_submnuServiciosActionPerformed

    private void submnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuarios formusuarios = new FrmUsuarios();
        Desktop.add(formusuarios);
        formusuarios.setVisible(true);
    }//GEN-LAST:event_submnuUsuariosActionPerformed

    private void submnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuClientesActionPerformed
        // TODO add your handling code here:
        FrmCliente formcliente = new FrmCliente();
        Desktop.add(formcliente);
        formcliente.setVisible(true);
    }//GEN-LAST:event_submnuClientesActionPerformed

    private void submnuVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVehiculosActionPerformed
        // TODO add your handling code here:
        FrmVehiculos formvehiculos = new FrmVehiculos();
        Desktop.add(formvehiculos);
        formvehiculos.setVisible(true);
    }//GEN-LAST:event_submnuVehiculosActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void submnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVentasActionPerformed
        // TODO add your handling code here:
        FrmVenta formventa = new FrmVenta();
        Desktop.add(formventa);
        formventa.setVisible(true);
    }//GEN-LAST:event_submnuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuServicios;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem submnuClientes;
    private javax.swing.JMenuItem submnuRols;
    private javax.swing.JMenuItem submnuServicios;
    private javax.swing.JMenuItem submnuUsuarios;
    private javax.swing.JMenuItem submnuVehiculos;
    private javax.swing.JMenuItem submnuVentas;
    // End of variables declaration//GEN-END:variables
}
