/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.autolavado.view;

import com.mycompany.autolavado.controller.clienteController;
import com.mycompany.autolavado.controller.rolController;
import com.mycompany.autolavado.controller.servicioController;
import com.mycompany.autolavado.controller.vehiculoController;
import com.mycompany.autolavado.controller.ventaController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.clienteModel;
import model.rolModel;
import model.servicioModel;
import model.vehiculoModel;
import model.ventaModel;


/**
 *
 * @author CLEMENTE
 */
public class FrmVenta extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla;
    private int idVenta = 0;
    private int idUsuarioCObtenido = 2;//idUsuarioCliente
    private int idUsuarioLObtenido = 2;//idUsuarioRol
    private int idServicioObtenido = 2;//idServicio
    private int idVehiculoObtenido = 2;//idVehiculo
    
    /**
     * Creates new form Servicios
     */
    public FrmVenta() {
        super (" Venta", true,true,true,true);
        modeloTabla = new DefaultTableModel(new Object[]{"IdVenta","IdUsuarioC","IdUsuarioL","IdServicio","IdVehiculo","Fecha","Hora","Estatus","Pagado"},0);
        tblVenta = new JTable (modeloTabla);
        cargarVenta();
        initComponents();
        seleccionarVenta();
        obtenerRolCliente();
        obtenerIdRolCliente();
        obtenerRol();
        obtenerIdRol();
        obtenerRolServicio();
        obtenerIdRolServicio();
        obtenerRolVehiculo();
        obtenerIdRolVehiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboRolCliente = new javax.swing.JComboBox<>();
        cboRol = new javax.swing.JComboBox<>();
        cboRolServicio = new javax.swing.JComboBox<>();
        cboRolVehiculo = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        txtPagado = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelVentas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Id Usuario Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Usuario L Rol");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Id Servicio");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Id Vehiculo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hora");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Estatus");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Pagado");

        txtPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagadoActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblVenta.setModel(modeloTabla);
        jScrollPane1.setViewportView(tblVenta);

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboRolServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboRolVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVentasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboRolCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                            .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(7, 7, 7))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVentasLayout.createSequentialGroup()
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPagado, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtEstatus))
                                .addGap(51, 51, 51)))
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1)
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboRolCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(jLabel5))
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboRolServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboRolVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        agregarVenta();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarVenta();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        modificarVenta();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarVenta();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }
    public void agregarVenta(){
    
    String fecha = txtFecha.getText();
    String hora = txtHora.getText();
    String estatus = txtEstatus.getText();
    String pagado = txtPagado.getText();
// 🔹 Obtener ID del rol
    int idUsuarioC = idUsuarioCObtenido; // Asegúrate de mapearlo si es necesario
    int idUsuarioL = idUsuarioLObtenido;
    int idServicio = idServicioObtenido;
    int idVehiculo = idVehiculoObtenido;
    
    if(fecha.isEmpty() || pagado.isEmpty()){
        JOptionPane.showConfirmDialog(this,"Ingresa los Datos");
    }else{
        ventaController.insertarVenta(new ventaModel(idUsuarioC,idUsuarioL,idServicio,idVehiculo,fecha,hora,estatus,pagado));
        txtFecha.setText("");
        txtHora.setText("");
        txtEstatus.setText("");
        txtPagado.setText("");
        
        cargarVenta();
    }
}
    public void cargarVenta(){
        modeloTabla.setRowCount(0);
        List<ventaModel> ventas = ventaController.obtenerTodos();
        for(ventaModel r : ventas){
            modeloTabla.addRow(new Object[]{r.getIdVenta(),r.getIdUsuarioC(),r.getIdUsuarioL(),r.getIdServicio(),r.getIdVehiculo(),r.getFecha(),r.getHora(),r.getEstatus(),r.getPagado()});
        }
    }
    private void seleccionarVenta(){
    tblVenta.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int fila = tblVenta.getSelectedRow();
            if (fila != -1) {
                idVenta = Integer.parseInt(tblVenta.getValueAt(fila, 0).toString());
                
                txtFecha.setText(tblVenta.getValueAt(fila, 5).toString());
                txtHora.setText(tblVenta.getValueAt(fila, 6).toString());
                txtEstatus.setText(tblVenta.getValueAt(fila, 7).toString());
                txtPagado.setText(tblVenta.getValueAt(fila, 8).toString());
                

                // Suponiendo que el ComboBox tiene los mismos valores
            } else {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún usuario.");
            }
        }
    });
}
    public void buscarVenta(){
        String pagado = JOptionPane.showInputDialog(this,"Introduce el Pago");
        modeloTabla.setRowCount(0);
        List<ventaModel> ventas = ventaController.buscarVentaPorNombre(pagado);
        for(ventaModel r : ventas){
            modeloTabla.addRow(new Object[]{r.getIdVenta(),r.getIdUsuarioC(),r.getIdUsuarioL(),r.getIdServicio(),r.getIdVehiculo(),r.getFecha(),r.getHora(),r.getEstatus(),r.getPagado()});
        }
    }
    private void modificarVenta(){
        
    String fecha = txtFecha.getText();
    String hora = txtHora.getText();
    String estatus = txtEstatus.getText();
    String pagado = txtPagado.getText();
// 🔹 Obtener fecha de nacimiento
    

// 🔹 Obtener ID del rol
    int idUsuarioC = idUsuarioCObtenido; // Asegúrate de mapearlo si es necesario
    int idUsuarioL = idUsuarioLObtenido;
    int idServicio = idServicioObtenido;
    int idVehiculo = idVehiculoObtenido;
    
    if(estatus.isEmpty() || pagado.isEmpty()){
        JOptionPane.showConfirmDialog(this,"Ingresa los Datos");
    }else{
        ventaController.actualizarVenta(new ventaModel(this.idVenta,idUsuarioC,idUsuarioL,idServicio,idVehiculo,fecha,hora,estatus,pagado));
        txtFecha.setText("");
        txtHora.setText("");
        txtEstatus.setText("");
        txtPagado.setText("");
        
        cargarVenta();
    }
        
    }
    private void obtenerRolCliente(){
        cboRolCliente.removeAllItems();
        List<clienteModel> clientes = clienteController.obtenerTodos();
        for(clienteModel cliente: clientes){
            cboRolCliente.addItem(cliente);
        }
    }
    private void obtenerIdRolCliente(){
        cboRolCliente.addActionListener(e ->{
            clienteModel seleccionado = (clienteModel) cboRolCliente.getSelectedItem();
            if(seleccionado != null){
                idUsuarioCObtenido = seleccionado.getIdCliente();
            }
        });
    }
    private void obtenerRol(){
        cboRol.removeAllItems();
        List<rolModel> roles = rolController.obtenerTodos();
        for(rolModel rol: roles){
            cboRol.addItem(rol);
        }
    }
    private void obtenerIdRol(){
        cboRol.addActionListener(e ->{
            rolModel seleccionado = (rolModel) cboRol.getSelectedItem();
            if(seleccionado != null){
                idUsuarioLObtenido = seleccionado.getIdRol();
            }
        });
    }
    private void obtenerRolServicio(){
        cboRolServicio.removeAllItems();
        List<servicioModel> servicios = servicioController.obtenerTodos();
        for(servicioModel servicio: servicios){
            cboRolServicio.addItem(servicio);
        }
    }
    private void obtenerIdRolServicio(){
        cboRolServicio.addActionListener(e ->{
            servicioModel seleccionado = (servicioModel) cboRolServicio.getSelectedItem();
            if(seleccionado != null){
                idServicioObtenido = seleccionado.getIdServicio();
            }
        });
    }
    private void obtenerRolVehiculo(){
        cboRolVehiculo.removeAllItems();
        List<vehiculoModel> vehiculos = vehiculoController.obtenerTodos();
        for(vehiculoModel vehiculo: vehiculos){
            cboRolVehiculo.addItem(vehiculo);
        }
    }
    private void obtenerIdRolVehiculo(){
        cboRolVehiculo.addActionListener(e ->{
            vehiculoModel seleccionado = (vehiculoModel) cboRolVehiculo.getSelectedItem();
            if(seleccionado != null){
                idVehiculoObtenido = seleccionado.getIdVehiculo();
            }
        });
    }
    private void eliminarVenta(){
        int fila = tblVenta.getSelectedRow();
        if(fila != -1){
            int id= Integer.parseInt(tblVenta.getValueAt(fila,0).toString());
            ventaController.eliminarVenta(id);
            cargarVenta();
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona la Venta a eliminar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<rolModel> cboRol;
    private javax.swing.JComboBox<clienteModel> cboRolCliente;
    private javax.swing.JComboBox<servicioModel> cboRolServicio;
    private javax.swing.JComboBox<vehiculoModel> cboRolVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenta;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtPagado;
    // End of variables declaration//GEN-END:variables
}
